alter table BLOG_PUBLICATION add constraint FK_BLOG_PUBLICATION_ON_AUTHOR foreign key (AUTHOR_ID) references BLOG_AUTHOR(ID);
create index IDX_BLOG_PUBLICATION_ON_AUTHOR on BLOG_PUBLICATION (AUTHOR_ID);
